# Generated by Django 6.0.5 on 2026-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('balanced', 'Balanced'), ('keto', 'Keto'), ('vegan', 'Vegan')], max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
