# Generated by Django 6.0.5 on 2026-05-15 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField()),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('body_type', models.CharField(choices=[('ectomorph', 'Ectomorph'), ('mesomorph', 'Mesomorph'), ('endomorph', 'Endomorph')], max_length=30)),
                ('calories_needed', models.IntegerField()),
                ('protein_needed', models.IntegerField()),
                ('carbs_needed', models.IntegerField()),
                ('fats_needed', models.IntegerField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_analysis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
