# Generated by Django 6.0.5 on 2026-05-15 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_calories', models.IntegerField(default=0)),
                ('burned_calories', models.IntegerField(default=0)),
                ('water_intake', models.FloatField(default=0)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('completed_diet', models.BooleanField(default=False)),
                ('tracking_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tracking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
